pack_hosting:
  resource_pack_prompt: "Download the Lost Engine resource pack"
  self_hosted:
    enabled: true
    hostname: 0.0.0.0
    port: 7270
  external_host:
    enabled: false
    url: ""
resource_pack:
  file_name: "resource-pack"
  glyphs:
    offset_characters: # Java Edition only
      enabled: true
      # from -1023 to 1023 will use 20 characters (6400 characters available in total)
      from: -1023
      to: 1023

inject_custom_materials: true
geyser_compatibility: false